name = "stiff3"
version = "0.1.0"
license = "Apache-2.0"
maintainer = "ivan.pribec@gmail.com"
author = ["John Villadsen", "Michael L. Michelsen"]
description = "Adaptive solver for stiff systems of ODEs"
keywords = ["ode","solver","runge-kutta"]

[build]
link = ["lapack", "blas"]
