name: test

on: [push, pull_request]

jobs:
  gfortran-nix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-11]
        gcc_v: [9]
        include:
        - os: ubuntu-latest
          os-arch: linux-x86_64
          release-flags: --flag '--static -g -fbacktrace -O2'
        - os: macos-11
          os-arch: macos-x86_64
          release-flags: --flag '-g -fbacktrace -O2'

    env:
      FC: gfortran
      GCC_V: ${{ matrix.gcc_v }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install GFortran macOS
      if: contains(matrix.os, 'macos')
      run: |
          ln -s /usr/local/bin/gfortran-${GCC_V} /usr/local/bin/gfortran
          which gfortran-${GCC_V}
          which gfortran

    - name: Install GFortran Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_V} 100 \
        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V} \
        --slave /usr/bingcov gcov /usr/bin/gcov-${GCC_V}

    - name: Install fpm
      uses: fortran-lang/setup-fpm@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run example programs (release)
      run: |
        gfortran --version
        fpm build ${{ matrix.release-flags }}
        fpm run --example robertson
        fpm run --example vanpol